Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Country Other Info Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "ff9baac8-13d8-4a15-bf3e-007b01b98b62", "6174582c-29a2-4afd-a919-9457c862baa2", "Country Extention")> _
Partial Public Class [CountryOtherInfoEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _majorholidaysandfestivals As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _culturaltraditions As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childmortalityrateunderfive As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _infantmortalityrate As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _annualincomepercapita As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _percentpopulationlivinglessthanonedollar As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _lifeexpectancyatbirth As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _fertilityrate As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _adultliteracyrate As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _netprimaryschoolenrollmentattendance As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _percentchildrenreachinggradefive As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _childlaborpercentage As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentinfantslowbirthrate As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentchildrenunderfiveunderweight As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentchildrenunderfivewastingstunted As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percenturbanpopulationusingimprovedwater As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentrualpopulationusingimprovedwater As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percenttotalpopulationusingimprovedwater As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percenturbanpopulationusingadequatesanitation As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentruralpopulationusingadequatesanitation As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percenttotalpopulationusingadequatesanitation As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _hivaidsadultprevalencerate As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _numberpeoplelivingwithivaids As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _majorholidaysandfestivals = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _culturaltraditions = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childmortalityrateunderfive = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _infantmortalityrate = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _annualincomepercapita = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _percentpopulationlivinglessthanonedollar = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _lifeexpectancyatbirth = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _fertilityrate = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _adultliteracyrate = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _netprimaryschoolenrollmentattendance = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _percentchildrenreachinggradefive = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _childlaborpercentage = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentinfantslowbirthrate = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentchildrenunderfiveunderweight = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentchildrenunderfivewastingstunted = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percenturbanpopulationusingimprovedwater = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentrualpopulationusingimprovedwater = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percenttotalpopulationusingimprovedwater = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percenturbanpopulationusingadequatesanitation = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentruralpopulationusingadequatesanitation = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percenttotalpopulationusingadequatesanitation = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _hivaidsadultprevalencerate = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _numberpeoplelivingwithivaids = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("ff9baac8-13d8-4a15-bf3e-007b01b98b62")
        MyBase.DataFormInstanceId = New Guid("6174582c-29a2-4afd-a919-9457c862baa2")
        MyBase.RecordType = "Country Extention"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/Country.OtherInfo.EditForm.html"

        '
        '_majorholidaysandfestivals
        '
        _majorholidaysandfestivals.Name = "MAJORHOLIDAYSANDFESTIVALS"
        _majorholidaysandfestivals.Caption = "Major holidays and festivals"
        _majorholidaysandfestivals.MaxLength = 1000
        _majorholidaysandfestivals.MultiLine = True
        Me.Fields.Add(_majorholidaysandfestivals)
        '
        '_culturaltraditions
        '
        _culturaltraditions.Name = "CULTURALTRADITIONS"
        _culturaltraditions.Caption = "Cultural traditions"
        _culturaltraditions.MaxLength = 1000
        _culturaltraditions.MultiLine = True
        Me.Fields.Add(_culturaltraditions)
        '
        '_childmortalityrateunderfive
        '
        _childmortalityrateunderfive.Name = "CHILDMORTALITYRATEUNDERFIVE"
        _childmortalityrateunderfive.Caption = "Mortality rate of children under age five"
        Me.Fields.Add(_childmortalityrateunderfive)
        '
        '_infantmortalityrate
        '
        _infantmortalityrate.Name = "INFANTMORTALITYRATE"
        _infantmortalityrate.Caption = "Infant mortality rate"
        Me.Fields.Add(_infantmortalityrate)
        '
        '_annualincomepercapita
        '
        _annualincomepercapita.Name = "ANNUALINCOMEPERCAPITA"
        _annualincomepercapita.Caption = "Annual income per capita"
        Me.Fields.Add(_annualincomepercapita)
        '
        '_percentpopulationlivinglessthanonedollar
        '
        _percentpopulationlivinglessthanonedollar.Name = "PERCENTPOPULATIONLIVINGLESSTHANONEDOLLAR"
        _percentpopulationlivinglessthanonedollar.Caption = "Percent of population living on less than the equivalent of one US dollar per day"
        Me.Fields.Add(_percentpopulationlivinglessthanonedollar)
        '
        '_lifeexpectancyatbirth
        '
        _lifeexpectancyatbirth.Name = "LIFEEXPECTANCYATBIRTH"
        _lifeexpectancyatbirth.Caption = "Life expectancy at birth"
        Me.Fields.Add(_lifeexpectancyatbirth)
        '
        '_fertilityrate
        '
        _fertilityrate.Name = "FERTILITYRATE"
        _fertilityrate.Caption = "Fertility rate"
        Me.Fields.Add(_fertilityrate)
        '
        '_adultliteracyrate
        '
        _adultliteracyrate.Name = "ADULTLITERACYRATE"
        _adultliteracyrate.Caption = "Adult literacy rate"
        Me.Fields.Add(_adultliteracyrate)
        '
        '_netprimaryschoolenrollmentattendance
        '
        _netprimaryschoolenrollmentattendance.Name = "NETPRIMARYSCHOOLENROLLMENTATTENDANCE"
        _netprimaryschoolenrollmentattendance.Caption = "Net primary school enrollment/attendance"
        Me.Fields.Add(_netprimaryschoolenrollmentattendance)
        '
        '_percentchildrenreachinggradefive
        '
        _percentchildrenreachinggradefive.Name = "PERCENTCHILDRENREACHINGGRADEFIVE"
        _percentchildrenreachinggradefive.Caption = "Percent of children reaching grade five"
        Me.Fields.Add(_percentchildrenreachinggradefive)
        '
        '_childlaborpercentage
        '
        _childlaborpercentage.Name = "CHILDLABORPERCENTAGE"
        _childlaborpercentage.Caption = "Child Labor Percentage"
        Me.Fields.Add(_childlaborpercentage)
        '
        '_percentinfantslowbirthrate
        '
        _percentinfantslowbirthrate.Name = "PERCENTINFANTSLOWBIRTHRATE"
        _percentinfantslowbirthrate.Caption = "Percent of infants with low birth weight"
        Me.Fields.Add(_percentinfantslowbirthrate)
        '
        '_percentchildrenunderfiveunderweight
        '
        _percentchildrenunderfiveunderweight.Name = "PERCENTCHILDRENUNDERFIVEUNDERWEIGHT"
        _percentchildrenunderfiveunderweight.Caption = "Percent of children under age five that are underweight"
        Me.Fields.Add(_percentchildrenunderfiveunderweight)
        '
        '_percentchildrenunderfivewastingstunted
        '
        _percentchildrenunderfivewastingstunted.Name = "PERCENTCHILDRENUNDERFIVEWASTINGSTUNTED"
        _percentchildrenunderfivewastingstunted.Caption = "Percent of children under age five that are wasting or stunted"
        Me.Fields.Add(_percentchildrenunderfivewastingstunted)
        '
        '_percenturbanpopulationusingimprovedwater
        '
        _percenturbanpopulationusingimprovedwater.Name = "PERCENTURBANPOPULATIONUSINGIMPROVEDWATER"
        _percenturbanpopulationusingimprovedwater.Caption = "Percent of urban population using improved water sources"
        Me.Fields.Add(_percenturbanpopulationusingimprovedwater)
        '
        '_percentrualpopulationusingimprovedwater
        '
        _percentrualpopulationusingimprovedwater.Name = "PERCENTRUALPOPULATIONUSINGIMPROVEDWATER"
        _percentrualpopulationusingimprovedwater.Caption = "Percent of rural population using improved water sources"
        Me.Fields.Add(_percentrualpopulationusingimprovedwater)
        '
        '_percenttotalpopulationusingimprovedwater
        '
        _percenttotalpopulationusingimprovedwater.Name = "PERCENTTOTALPOPULATIONUSINGIMPROVEDWATER"
        _percenttotalpopulationusingimprovedwater.Caption = "Percent of total population using improved water sources"
        Me.Fields.Add(_percenttotalpopulationusingimprovedwater)
        '
        '_percenturbanpopulationusingadequatesanitation
        '
        _percenturbanpopulationusingadequatesanitation.Name = "PERCENTURBANPOPULATIONUSINGADEQUATESANITATION"
        _percenturbanpopulationusingadequatesanitation.Caption = "Percent of urban population using adequate sanitation facilities"
        Me.Fields.Add(_percenturbanpopulationusingadequatesanitation)
        '
        '_percentruralpopulationusingadequatesanitation
        '
        _percentruralpopulationusingadequatesanitation.Name = "PERCENTRURALPOPULATIONUSINGADEQUATESANITATION"
        _percentruralpopulationusingadequatesanitation.Caption = "Percent of rural population using adequate sanitation facilities"
        Me.Fields.Add(_percentruralpopulationusingadequatesanitation)
        '
        '_percenttotalpopulationusingadequatesanitation
        '
        _percenttotalpopulationusingadequatesanitation.Name = "PERCENTTOTALPOPULATIONUSINGADEQUATESANITATION"
        _percenttotalpopulationusingadequatesanitation.Caption = "Percent of total population using adequate sanitation facilities"
        Me.Fields.Add(_percenttotalpopulationusingadequatesanitation)
        '
        '_hivaidsadultprevalencerate
        '
        _hivaidsadultprevalencerate.Name = "HIVAIDSADULTPREVALENCERATE"
        _hivaidsadultprevalencerate.Caption = "HIV/AIDS adult prevalence rate"
        Me.Fields.Add(_hivaidsadultprevalencerate)
        '
        '_numberpeoplelivingwithivaids
        '
        _numberpeoplelivingwithivaids.Name = "NUMBERPEOPLELIVINGWITHIVAIDS"
        _numberpeoplelivingwithivaids.Caption = "Number of people living with HIV/AIDS"
        Me.Fields.Add(_numberpeoplelivingwithivaids)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Major holidays and festivals
    ''' </summary>
    <System.ComponentModel.Description("Major holidays and festivals")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MAJORHOLIDAYSANDFESTIVALS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _majorholidaysandfestivals
        End Get
    End Property
    
    ''' <summary>
    ''' Cultural traditions
    ''' </summary>
    <System.ComponentModel.Description("Cultural traditions")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CULTURALTRADITIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _culturaltraditions
        End Get
    End Property
    
    ''' <summary>
    ''' Mortality rate of children under age five
    ''' </summary>
    <System.ComponentModel.Description("Mortality rate of children under age five")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDMORTALITYRATEUNDERFIVE]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _childmortalityrateunderfive
        End Get
    End Property
    
    ''' <summary>
    ''' Infant mortality rate
    ''' </summary>
    <System.ComponentModel.Description("Infant mortality rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [INFANTMORTALITYRATE]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _infantmortalityrate
        End Get
    End Property
    
    ''' <summary>
    ''' Annual income per capita
    ''' </summary>
    <System.ComponentModel.Description("Annual income per capita")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ANNUALINCOMEPERCAPITA]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _annualincomepercapita
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of population living on less than the equivalent of one US dollar per day
    ''' </summary>
    <System.ComponentModel.Description("Percent of population living on less than the equivalent of one US dollar per day")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTPOPULATIONLIVINGLESSTHANONEDOLLAR]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentpopulationlivinglessthanonedollar
        End Get
    End Property
    
    ''' <summary>
    ''' Life expectancy at birth
    ''' </summary>
    <System.ComponentModel.Description("Life expectancy at birth")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LIFEEXPECTANCYATBIRTH]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _lifeexpectancyatbirth
        End Get
    End Property
    
    ''' <summary>
    ''' Fertility rate
    ''' </summary>
    <System.ComponentModel.Description("Fertility rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FERTILITYRATE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _fertilityrate
        End Get
    End Property
    
    ''' <summary>
    ''' Adult literacy rate
    ''' </summary>
    <System.ComponentModel.Description("Adult literacy rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADULTLITERACYRATE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _adultliteracyrate
        End Get
    End Property
    
    ''' <summary>
    ''' Net primary school enrollment/attendance
    ''' </summary>
    <System.ComponentModel.Description("Net primary school enrollment/attendance")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NETPRIMARYSCHOOLENROLLMENTATTENDANCE]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _netprimaryschoolenrollmentattendance
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of children reaching grade five
    ''' </summary>
    <System.ComponentModel.Description("Percent of children reaching grade five")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTCHILDRENREACHINGGRADEFIVE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentchildrenreachinggradefive
        End Get
    End Property
    
    ''' <summary>
    ''' Child Labor Percentage
    ''' </summary>
    <System.ComponentModel.Description("Child Labor Percentage")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDLABORPERCENTAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _childlaborpercentage
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of infants with low birth weight
    ''' </summary>
    <System.ComponentModel.Description("Percent of infants with low birth weight")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTINFANTSLOWBIRTHRATE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentinfantslowbirthrate
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of children under age five that are underweight
    ''' </summary>
    <System.ComponentModel.Description("Percent of children under age five that are underweight")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTCHILDRENUNDERFIVEUNDERWEIGHT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentchildrenunderfiveunderweight
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of children under age five that are wasting or stunted
    ''' </summary>
    <System.ComponentModel.Description("Percent of children under age five that are wasting or stunted")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTCHILDRENUNDERFIVEWASTINGSTUNTED]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentchildrenunderfivewastingstunted
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of urban population using improved water sources
    ''' </summary>
    <System.ComponentModel.Description("Percent of urban population using improved water sources")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTURBANPOPULATIONUSINGIMPROVEDWATER]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percenturbanpopulationusingimprovedwater
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of rural population using improved water sources
    ''' </summary>
    <System.ComponentModel.Description("Percent of rural population using improved water sources")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTRUALPOPULATIONUSINGIMPROVEDWATER]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentrualpopulationusingimprovedwater
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of total population using improved water sources
    ''' </summary>
    <System.ComponentModel.Description("Percent of total population using improved water sources")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTTOTALPOPULATIONUSINGIMPROVEDWATER]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percenttotalpopulationusingimprovedwater
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of urban population using adequate sanitation facilities
    ''' </summary>
    <System.ComponentModel.Description("Percent of urban population using adequate sanitation facilities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTURBANPOPULATIONUSINGADEQUATESANITATION]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percenturbanpopulationusingadequatesanitation
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of rural population using adequate sanitation facilities
    ''' </summary>
    <System.ComponentModel.Description("Percent of rural population using adequate sanitation facilities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTRURALPOPULATIONUSINGADEQUATESANITATION]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentruralpopulationusingadequatesanitation
        End Get
    End Property
    
    ''' <summary>
    ''' Percent of total population using adequate sanitation facilities
    ''' </summary>
    <System.ComponentModel.Description("Percent of total population using adequate sanitation facilities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTTOTALPOPULATIONUSINGADEQUATESANITATION]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percenttotalpopulationusingadequatesanitation
        End Get
    End Property
    
    ''' <summary>
    ''' HIV/AIDS adult prevalence rate
    ''' </summary>
    <System.ComponentModel.Description("HIV/AIDS adult prevalence rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIVAIDSADULTPREVALENCERATE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _hivaidsadultprevalencerate
        End Get
    End Property
    
    ''' <summary>
    ''' Number of people living with HIV/AIDS
    ''' </summary>
    <System.ComponentModel.Description("Number of people living with HIV/AIDS")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NUMBERPEOPLELIVINGWITHIVAIDS]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _numberpeoplelivingwithivaids
        End Get
    End Property
    
End Class
