Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Country Extension View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "5b4584b5-8925-4401-b001-75895eeaf978", "1a997144-6598-47dc-966a-62ff307b0feb", "Country Extension")> _
Partial Public Class [CountryExtensionSummaryViewFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _fullcountryname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _countrycode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _countrystatuscode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _countrystatusdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _countryregioncode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _locationreportrecipients As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _fullcountryname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _countrycode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _countrystatuscode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _countrystatusdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _countryregioncode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _locationreportrecipients = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("5b4584b5-8925-4401-b001-75895eeaf978")
        MyBase.DataFormInstanceId = New Guid("1a997144-6598-47dc-966a-62ff307b0feb")
        MyBase.RecordType = "Country Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/Country.ExtensionSummary.ViewForm.html"

        '
        '_fullcountryname
        '
        _fullcountryname.Name = "FULLCOUNTRYNAME"
        _fullcountryname.Caption = "Name"
        _fullcountryname.DBReadOnly = True
        _fullcountryname.MaxLength = 50
        Me.Fields.Add(_fullcountryname)
        '
        '_countrycode
        '
        _countrycode.Name = "COUNTRYCODE"
        _countrycode.Caption = "ISO Country code"
        _countrycode.DBReadOnly = True
        _countrycode.MaxLength = 2
        Me.Fields.Add(_countrycode)
        '
        '_countrystatuscode
        '
        _countrystatuscode.Name = "COUNTRYSTATUSCODE"
        _countrystatuscode.Caption = "Status"
        _countrystatuscode.DBReadOnly = True
        _countrystatuscode.MaxLength = 100
        Me.Fields.Add(_countrystatuscode)
        '
        '_countrystatusdate
        '
        _countrystatusdate.Name = "COUNTRYSTATUSDATE"
        _countrystatusdate.Caption = "Status date"
        _countrystatusdate.DBReadOnly = True
        Me.Fields.Add(_countrystatusdate)
        '
        '_countryregioncode
        '
        _countryregioncode.Name = "COUNTRYREGIONCODE"
        _countryregioncode.Caption = "Region"
        _countryregioncode.DBReadOnly = True
        _countryregioncode.MaxLength = 100
        Me.Fields.Add(_countryregioncode)
        '
        '_locationreportrecipients
        '
        _locationreportrecipients.Name = "LOCATIONREPORTRECIPIENTS"
        _locationreportrecipients.Caption = "Report recipients"
        _locationreportrecipients.DBReadOnly = True
        Me.Fields.Add(_locationreportrecipients)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FULLCOUNTRYNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _fullcountryname
        End Get
    End Property
    
    ''' <summary>
    ''' ISO Country code
    ''' </summary>
    <System.ComponentModel.Description("ISO Country code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COUNTRYCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _countrycode
        End Get
    End Property
    
    ''' <summary>
    ''' Status
    ''' </summary>
    <System.ComponentModel.Description("Status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COUNTRYSTATUSCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _countrystatuscode
        End Get
    End Property
    
    ''' <summary>
    ''' Status date
    ''' </summary>
    <System.ComponentModel.Description("Status date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COUNTRYSTATUSDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _countrystatusdate
        End Get
    End Property
    
    ''' <summary>
    ''' Region
    ''' </summary>
    <System.ComponentModel.Description("Region")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COUNTRYREGIONCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _countryregioncode
        End Get
    End Property
    
    ''' <summary>
    ''' Report recipients
    ''' </summary>
    <System.ComponentModel.Description("Report recipients")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [LOCATIONREPORTRECIPIENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _locationreportrecipients
        End Get
    End Property
    
End Class
