Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Country Quota View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "2f388259-b0a5-40f3-bb86-4148e470565c", "2f3b5aa6-71cb-423b-9340-480ab2584c44", "Country Extension")> _
Partial Public Class [CountryQuotaViewFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _quotatype As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _quotatypecode As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _approvedquotainitial As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _currentquota As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _growthquota As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _decreasedquota As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota01oct As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota02nov As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota03dec As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota04jan As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota05feb As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota06mar As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota07apr As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota08may As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota09jun As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota10jul As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota11aug As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _approvedquota12sep As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _newchildrenstatus As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _performancecode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _marketingdemandstatus As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _overridetriggerstatus As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childrennotentered As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _quotatype = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _quotatypecode = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _approvedquotainitial = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _currentquota = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _growthquota = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _decreasedquota = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota01oct = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota02nov = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota03dec = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota04jan = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota05feb = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota06mar = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota07apr = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota08may = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota09jun = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota10jul = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota11aug = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _approvedquota12sep = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _newchildrenstatus = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _performancecode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _marketingdemandstatus = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _overridetriggerstatus = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childrennotentered = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("2f388259-b0a5-40f3-bb86-4148e470565c")
        MyBase.DataFormInstanceId = New Guid("2f3b5aa6-71cb-423b-9340-480ab2584c44")
        MyBase.RecordType = "Country Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/Country.Quota.ViewForm.html"

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        _id.DBReadOnly = True
        Me.Fields.Add(_id)
        '
        '_quotatype
        '
        _quotatype.Name = "QUOTATYPE"
        _quotatype.Caption = "Quota type"
        _quotatype.DBReadOnly = True
        _quotatype.MaxLength = 100
        Me.Fields.Add(_quotatype)
        '
        '_quotatypecode
        '
        _quotatypecode.Name = "QUOTATYPECODE"
        _quotatypecode.Caption = "Quota type code"
        _quotatypecode.Visible = False
        _quotatypecode.DBReadOnly = True
        Me.Fields.Add(_quotatypecode)
        '
        '_approvedquotainitial
        '
        _approvedquotainitial.Name = "APPROVEDQUOTAINITIAL"
        _approvedquotainitial.Caption = "Initial quota"
        _approvedquotainitial.DBReadOnly = True
        Me.Fields.Add(_approvedquotainitial)
        '
        '_currentquota
        '
        _currentquota.Name = "CURRENTQUOTA"
        _currentquota.Caption = "Current quota"
        _currentquota.DBReadOnly = True
        Me.Fields.Add(_currentquota)
        '
        '_growthquota
        '
        _growthquota.Name = "GROWTHQUOTA"
        _growthquota.Caption = "Growth quota"
        _growthquota.DBReadOnly = True
        Me.Fields.Add(_growthquota)
        '
        '_decreasedquota
        '
        _decreasedquota.Name = "DECREASEDQUOTA"
        _decreasedquota.Caption = "Decreased quota"
        _decreasedquota.DBReadOnly = True
        Me.Fields.Add(_decreasedquota)
        '
        '_approvedquota01oct
        '
        _approvedquota01oct.Name = "APPROVEDQUOTA01OCT"
        _approvedquota01oct.Caption = "01 - October"
        _approvedquota01oct.DBReadOnly = True
        Me.Fields.Add(_approvedquota01oct)
        '
        '_approvedquota02nov
        '
        _approvedquota02nov.Name = "APPROVEDQUOTA02NOV"
        _approvedquota02nov.Caption = "02 - November"
        _approvedquota02nov.DBReadOnly = True
        Me.Fields.Add(_approvedquota02nov)
        '
        '_approvedquota03dec
        '
        _approvedquota03dec.Name = "APPROVEDQUOTA03DEC"
        _approvedquota03dec.Caption = "03 - December"
        _approvedquota03dec.DBReadOnly = True
        Me.Fields.Add(_approvedquota03dec)
        '
        '_approvedquota04jan
        '
        _approvedquota04jan.Name = "APPROVEDQUOTA04JAN"
        _approvedquota04jan.Caption = "04 - January"
        _approvedquota04jan.DBReadOnly = True
        Me.Fields.Add(_approvedquota04jan)
        '
        '_approvedquota05feb
        '
        _approvedquota05feb.Name = "APPROVEDQUOTA05FEB"
        _approvedquota05feb.Caption = "05 - February"
        _approvedquota05feb.DBReadOnly = True
        Me.Fields.Add(_approvedquota05feb)
        '
        '_approvedquota06mar
        '
        _approvedquota06mar.Name = "APPROVEDQUOTA06MAR"
        _approvedquota06mar.Caption = "06 - March"
        _approvedquota06mar.DBReadOnly = True
        Me.Fields.Add(_approvedquota06mar)
        '
        '_approvedquota07apr
        '
        _approvedquota07apr.Name = "APPROVEDQUOTA07APR"
        _approvedquota07apr.Caption = "07 - April"
        _approvedquota07apr.DBReadOnly = True
        Me.Fields.Add(_approvedquota07apr)
        '
        '_approvedquota08may
        '
        _approvedquota08may.Name = "APPROVEDQUOTA08MAY"
        _approvedquota08may.Caption = "08 - May"
        _approvedquota08may.DBReadOnly = True
        Me.Fields.Add(_approvedquota08may)
        '
        '_approvedquota09jun
        '
        _approvedquota09jun.Name = "APPROVEDQUOTA09JUN"
        _approvedquota09jun.Caption = "09 - June"
        _approvedquota09jun.DBReadOnly = True
        Me.Fields.Add(_approvedquota09jun)
        '
        '_approvedquota10jul
        '
        _approvedquota10jul.Name = "APPROVEDQUOTA10JUL"
        _approvedquota10jul.Caption = "10 - July"
        _approvedquota10jul.DBReadOnly = True
        Me.Fields.Add(_approvedquota10jul)
        '
        '_approvedquota11aug
        '
        _approvedquota11aug.Name = "APPROVEDQUOTA11AUG"
        _approvedquota11aug.Caption = "11 - August"
        _approvedquota11aug.DBReadOnly = True
        Me.Fields.Add(_approvedquota11aug)
        '
        '_approvedquota12sep
        '
        _approvedquota12sep.Name = "APPROVEDQUOTA12SEP"
        _approvedquota12sep.Caption = "12 - September"
        _approvedquota12sep.DBReadOnly = True
        Me.Fields.Add(_approvedquota12sep)
        '
        '_newchildrenstatus
        '
        _newchildrenstatus.Name = "NEWCHILDRENSTATUS"
        _newchildrenstatus.Caption = "New children status"
        _newchildrenstatus.DBReadOnly = True
        _newchildrenstatus.MaxLength = 20
        Me.Fields.Add(_newchildrenstatus)
        '
        '_performancecode
        '
        _performancecode.Name = "PERFORMANCECODE"
        _performancecode.Caption = "Performance"
        _performancecode.DBReadOnly = True
        _performancecode.MaxLength = 100
        Me.Fields.Add(_performancecode)
        '
        '_marketingdemandstatus
        '
        _marketingdemandstatus.Name = "MARKETINGDEMANDSTATUS"
        _marketingdemandstatus.Caption = "Marketing demand status"
        _marketingdemandstatus.DBReadOnly = True
        _marketingdemandstatus.MaxLength = 20
        Me.Fields.Add(_marketingdemandstatus)
        '
        '_overridetriggerstatus
        '
        _overridetriggerstatus.Name = "OVERRIDETRIGGERSTATUS"
        _overridetriggerstatus.Caption = "Override trigger status"
        _overridetriggerstatus.DBReadOnly = True
        _overridetriggerstatus.MaxLength = 20
        Me.Fields.Add(_overridetriggerstatus)
        '
        '_childrennotentered
        '
        _childrennotentered.Name = "CHILDRENNOTENTERED"
        _childrennotentered.Caption = "Children not entered"
        _childrennotentered.DBReadOnly = True
        Me.Fields.Add(_childrennotentered)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    ''' <summary>
    ''' Quota type
    ''' </summary>
    <System.ComponentModel.Description("Quota type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [QUOTATYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _quotatype
        End Get
    End Property
    
    ''' <summary>
    ''' Quota type code
    ''' </summary>
    <System.ComponentModel.Description("Quota type code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [QUOTATYPECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _quotatypecode
        End Get
    End Property
    
    ''' <summary>
    ''' Initial quota
    ''' </summary>
    <System.ComponentModel.Description("Initial quota")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTAINITIAL]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquotainitial
        End Get
    End Property
    
    ''' <summary>
    ''' Current quota
    ''' </summary>
    <System.ComponentModel.Description("Current quota")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CURRENTQUOTA]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _currentquota
        End Get
    End Property
    
    ''' <summary>
    ''' Growth quota
    ''' </summary>
    <System.ComponentModel.Description("Growth quota")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [GROWTHQUOTA]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _growthquota
        End Get
    End Property
    
    ''' <summary>
    ''' Decreased quota
    ''' </summary>
    <System.ComponentModel.Description("Decreased quota")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DECREASEDQUOTA]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _decreasedquota
        End Get
    End Property
    
    ''' <summary>
    ''' 01 - October
    ''' </summary>
    <System.ComponentModel.Description("01 - October")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA01OCT]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota01oct
        End Get
    End Property
    
    ''' <summary>
    ''' 02 - November
    ''' </summary>
    <System.ComponentModel.Description("02 - November")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA02NOV]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota02nov
        End Get
    End Property
    
    ''' <summary>
    ''' 03 - December
    ''' </summary>
    <System.ComponentModel.Description("03 - December")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA03DEC]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota03dec
        End Get
    End Property
    
    ''' <summary>
    ''' 04 - January
    ''' </summary>
    <System.ComponentModel.Description("04 - January")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA04JAN]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota04jan
        End Get
    End Property
    
    ''' <summary>
    ''' 05 - February
    ''' </summary>
    <System.ComponentModel.Description("05 - February")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA05FEB]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota05feb
        End Get
    End Property
    
    ''' <summary>
    ''' 06 - March
    ''' </summary>
    <System.ComponentModel.Description("06 - March")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA06MAR]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota06mar
        End Get
    End Property
    
    ''' <summary>
    ''' 07 - April
    ''' </summary>
    <System.ComponentModel.Description("07 - April")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA07APR]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota07apr
        End Get
    End Property
    
    ''' <summary>
    ''' 08 - May
    ''' </summary>
    <System.ComponentModel.Description("08 - May")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA08MAY]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota08may
        End Get
    End Property
    
    ''' <summary>
    ''' 09 - June
    ''' </summary>
    <System.ComponentModel.Description("09 - June")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA09JUN]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota09jun
        End Get
    End Property
    
    ''' <summary>
    ''' 10 - July
    ''' </summary>
    <System.ComponentModel.Description("10 - July")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA10JUL]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota10jul
        End Get
    End Property
    
    ''' <summary>
    ''' 11 - August
    ''' </summary>
    <System.ComponentModel.Description("11 - August")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA11AUG]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota11aug
        End Get
    End Property
    
    ''' <summary>
    ''' 12 - September
    ''' </summary>
    <System.ComponentModel.Description("12 - September")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [APPROVEDQUOTA12SEP]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _approvedquota12sep
        End Get
    End Property
    
    ''' <summary>
    ''' New children status
    ''' </summary>
    <System.ComponentModel.Description("New children status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [NEWCHILDRENSTATUS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _newchildrenstatus
        End Get
    End Property
    
    ''' <summary>
    ''' Performance
    ''' </summary>
    <System.ComponentModel.Description("Performance")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PERFORMANCECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _performancecode
        End Get
    End Property
    
    ''' <summary>
    ''' Marketing demand status
    ''' </summary>
    <System.ComponentModel.Description("Marketing demand status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MARKETINGDEMANDSTATUS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _marketingdemandstatus
        End Get
    End Property
    
    ''' <summary>
    ''' Override trigger status
    ''' </summary>
    <System.ComponentModel.Description("Override trigger status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OVERRIDETRIGGERSTATUS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _overridetriggerstatus
        End Get
    End Property
    
    ''' <summary>
    ''' Children not entered
    ''' </summary>
    <System.ComponentModel.Description("Children not entered")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHILDRENNOTENTERED]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _childrennotentered
        End Get
    End Property
    
End Class
