Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Country Demographics Edit Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "7fb760e9-e9c5-4644-a26d-20226b6f8194", "0e1898c7-f153-48f3-9a2b-972e80278463", "Country Extention")> _
Partial Public Class [CountryDemographicsEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _areainsquarekm As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _urbanpopulation As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _ruralpopulation As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _totalpopulation As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _peoplegroups As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _majortopographicalfeaturecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _languageamharic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagearabic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagebengali As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageburmese As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagechinese As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagecreole As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageenglish As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagefrench As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagehindi As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagekhmer As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagekirghiz As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagelao As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagenepali As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageromanian As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagerussian As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagesinhalese As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagesiswati As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagespanish As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageswahili As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagetagalog As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagetamil As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languagethai As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageurdu As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _languageotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _religionanimist As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionbuddhist As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religioncatholic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religioncoptic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionhindu As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionmuslim As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionorthodox As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionprotestant As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionvoodoo As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionwitchcraft As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _religionotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _governmentcapitalist As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentcommunist As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentdemocracy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentdictatorship As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentmonarchy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentrepublic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentrevolutionary As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentsocialist As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmenttransitional As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _governmentotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _areainsquarekm = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _urbanpopulation = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _ruralpopulation = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _totalpopulation = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _peoplegroups = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _majortopographicalfeaturecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _languageamharic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagearabic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagebengali = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageburmese = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagechinese = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagecreole = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageenglish = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagefrench = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagehindi = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagekhmer = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagekirghiz = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagelao = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagenepali = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageromanian = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagerussian = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagesinhalese = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagesiswati = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagespanish = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageswahili = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagetagalog = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagetamil = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languagethai = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageurdu = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _languageotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _religionanimist = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionbuddhist = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religioncatholic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religioncoptic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionhindu = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionmuslim = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionorthodox = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionprotestant = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionvoodoo = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionwitchcraft = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _religionotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _governmentcapitalist = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentcommunist = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentdemocracy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentdictatorship = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentmonarchy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentrepublic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentrevolutionary = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentsocialist = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmenttransitional = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _governmentotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("7fb760e9-e9c5-4644-a26d-20226b6f8194")
        MyBase.DataFormInstanceId = New Guid("0e1898c7-f153-48f3-9a2b-972e80278463")
        MyBase.RecordType = "Country Extention"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/Country.Demographics.EditForm.html"

        '
        '_areainsquarekm
        '
        _areainsquarekm.Name = "AREAINSQUAREKM"
        _areainsquarekm.Caption = "Area in square km"
        Me.Fields.Add(_areainsquarekm)
        '
        '_urbanpopulation
        '
        _urbanpopulation.Name = "URBANPOPULATION"
        _urbanpopulation.Caption = "Urban population"
        Me.Fields.Add(_urbanpopulation)
        '
        '_ruralpopulation
        '
        _ruralpopulation.Name = "RURALPOPULATION"
        _ruralpopulation.Caption = "Rural population"
        Me.Fields.Add(_ruralpopulation)
        '
        '_totalpopulation
        '
        _totalpopulation.Name = "TOTALPOPULATION"
        _totalpopulation.Caption = "Total population"
        Me.Fields.Add(_totalpopulation)
        '
        '_peoplegroups
        '
        _peoplegroups.Name = "PEOPLEGROUPS"
        _peoplegroups.Caption = "People groups"
        _peoplegroups.MaxLength = 1000
        _peoplegroups.MultiLine = True
        Me.Fields.Add(_peoplegroups)
        '
        '_majortopographicalfeaturecodeid
        '
        _majortopographicalfeaturecodeid.Name = "MAJORTOPOGRAPHICALFEATURECODEID"
        _majortopographicalfeaturecodeid.Caption = "Major topographical feature"
        _majortopographicalfeaturecodeid.CodeTableName = "USR_MAJORTOPOGRAPHICALFEATURECODE"
        Me.Fields.Add(_majortopographicalfeaturecodeid)
        '
        '_languageamharic
        '
        _languageamharic.Name = "LANGUAGEAMHARIC"
        _languageamharic.Caption = "Amharic"
        Me.Fields.Add(_languageamharic)
        '
        '_languagearabic
        '
        _languagearabic.Name = "LANGUAGEARABIC"
        _languagearabic.Caption = "Arabic"
        Me.Fields.Add(_languagearabic)
        '
        '_languagebengali
        '
        _languagebengali.Name = "LANGUAGEBENGALI"
        _languagebengali.Caption = "Bengali"
        Me.Fields.Add(_languagebengali)
        '
        '_languageburmese
        '
        _languageburmese.Name = "LANGUAGEBURMESE"
        _languageburmese.Caption = "Burmese"
        Me.Fields.Add(_languageburmese)
        '
        '_languagechinese
        '
        _languagechinese.Name = "LANGUAGECHINESE"
        _languagechinese.Caption = "Chinese"
        Me.Fields.Add(_languagechinese)
        '
        '_languagecreole
        '
        _languagecreole.Name = "LANGUAGECREOLE"
        _languagecreole.Caption = "Creole"
        Me.Fields.Add(_languagecreole)
        '
        '_languageenglish
        '
        _languageenglish.Name = "LANGUAGEENGLISH"
        _languageenglish.Caption = "English"
        Me.Fields.Add(_languageenglish)
        '
        '_languagefrench
        '
        _languagefrench.Name = "LANGUAGEFRENCH"
        _languagefrench.Caption = "French"
        Me.Fields.Add(_languagefrench)
        '
        '_languagehindi
        '
        _languagehindi.Name = "LANGUAGEHINDI"
        _languagehindi.Caption = "Hindi"
        Me.Fields.Add(_languagehindi)
        '
        '_languagekhmer
        '
        _languagekhmer.Name = "LANGUAGEKHMER"
        _languagekhmer.Caption = "Khmer"
        Me.Fields.Add(_languagekhmer)
        '
        '_languagekirghiz
        '
        _languagekirghiz.Name = "LANGUAGEKIRGHIZ"
        _languagekirghiz.Caption = "Kirghiz"
        Me.Fields.Add(_languagekirghiz)
        '
        '_languagelao
        '
        _languagelao.Name = "LANGUAGELAO"
        _languagelao.Caption = "Lao"
        Me.Fields.Add(_languagelao)
        '
        '_languagenepali
        '
        _languagenepali.Name = "LANGUAGENEPALI"
        _languagenepali.Caption = "Nepali"
        Me.Fields.Add(_languagenepali)
        '
        '_languageromanian
        '
        _languageromanian.Name = "LANGUAGEROMANIAN"
        _languageromanian.Caption = "Romanian"
        Me.Fields.Add(_languageromanian)
        '
        '_languagerussian
        '
        _languagerussian.Name = "LANGUAGERUSSIAN"
        _languagerussian.Caption = "Russian"
        Me.Fields.Add(_languagerussian)
        '
        '_languagesinhalese
        '
        _languagesinhalese.Name = "LANGUAGESINHALESE"
        _languagesinhalese.Caption = "Inhalese"
        Me.Fields.Add(_languagesinhalese)
        '
        '_languagesiswati
        '
        _languagesiswati.Name = "LANGUAGESISWATI"
        _languagesiswati.Caption = "Siswati"
        Me.Fields.Add(_languagesiswati)
        '
        '_languagespanish
        '
        _languagespanish.Name = "LANGUAGESPANISH"
        _languagespanish.Caption = "Spanish"
        Me.Fields.Add(_languagespanish)
        '
        '_languageswahili
        '
        _languageswahili.Name = "LANGUAGESWAHILI"
        _languageswahili.Caption = "Swahili"
        Me.Fields.Add(_languageswahili)
        '
        '_languagetagalog
        '
        _languagetagalog.Name = "LANGUAGETAGALOG"
        _languagetagalog.Caption = "Tagalog"
        Me.Fields.Add(_languagetagalog)
        '
        '_languagetamil
        '
        _languagetamil.Name = "LANGUAGETAMIL"
        _languagetamil.Caption = "Tamil"
        Me.Fields.Add(_languagetamil)
        '
        '_languagethai
        '
        _languagethai.Name = "LANGUAGETHAI"
        _languagethai.Caption = "Thai"
        Me.Fields.Add(_languagethai)
        '
        '_languageurdu
        '
        _languageurdu.Name = "LANGUAGEURDU"
        _languageurdu.Caption = "Urdu"
        Me.Fields.Add(_languageurdu)
        '
        '_languageother
        '
        _languageother.Name = "LANGUAGEOTHER"
        _languageother.Caption = "Other"
        Me.Fields.Add(_languageother)
        '
        '_languageotherdesc
        '
        _languageotherdesc.Name = "LANGUAGEOTHERDESC"
        _languageotherdesc.Caption = "Language other description"
        _languageotherdesc.MaxLength = 50
        Me.Fields.Add(_languageotherdesc)
        '
        '_religionanimist
        '
        _religionanimist.Name = "RELIGIONANIMIST"
        _religionanimist.Caption = "Animist"
        Me.Fields.Add(_religionanimist)
        '
        '_religionbuddhist
        '
        _religionbuddhist.Name = "RELIGIONBUDDHIST"
        _religionbuddhist.Caption = "Buddhist"
        Me.Fields.Add(_religionbuddhist)
        '
        '_religioncatholic
        '
        _religioncatholic.Name = "RELIGIONCATHOLIC"
        _religioncatholic.Caption = "Catholic"
        Me.Fields.Add(_religioncatholic)
        '
        '_religioncoptic
        '
        _religioncoptic.Name = "RELIGIONCOPTIC"
        _religioncoptic.Caption = "Coptic"
        Me.Fields.Add(_religioncoptic)
        '
        '_religionhindu
        '
        _religionhindu.Name = "RELIGIONHINDU"
        _religionhindu.Caption = "Hindu"
        Me.Fields.Add(_religionhindu)
        '
        '_religionmuslim
        '
        _religionmuslim.Name = "RELIGIONMUSLIM"
        _religionmuslim.Caption = "Muslim"
        Me.Fields.Add(_religionmuslim)
        '
        '_religionorthodox
        '
        _religionorthodox.Name = "RELIGIONORTHODOX"
        _religionorthodox.Caption = "Orthodox"
        Me.Fields.Add(_religionorthodox)
        '
        '_religionprotestant
        '
        _religionprotestant.Name = "RELIGIONPROTESTANT"
        _religionprotestant.Caption = "Protestant"
        Me.Fields.Add(_religionprotestant)
        '
        '_religionvoodoo
        '
        _religionvoodoo.Name = "RELIGIONVOODOO"
        _religionvoodoo.Caption = "Voodoo"
        Me.Fields.Add(_religionvoodoo)
        '
        '_religionwitchcraft
        '
        _religionwitchcraft.Name = "RELIGIONWITCHCRAFT"
        _religionwitchcraft.Caption = "Witchcraft"
        Me.Fields.Add(_religionwitchcraft)
        '
        '_religionother
        '
        _religionother.Name = "RELIGIONOTHER"
        _religionother.Caption = "Other"
        Me.Fields.Add(_religionother)
        '
        '_religionotherdesc
        '
        _religionotherdesc.Name = "RELIGIONOTHERDESC"
        _religionotherdesc.Caption = "Religion other description"
        _religionotherdesc.MaxLength = 50
        Me.Fields.Add(_religionotherdesc)
        '
        '_governmentcapitalist
        '
        _governmentcapitalist.Name = "GOVERNMENTCAPITALIST"
        _governmentcapitalist.Caption = "Capitalist"
        Me.Fields.Add(_governmentcapitalist)
        '
        '_governmentcommunist
        '
        _governmentcommunist.Name = "GOVERNMENTCOMMUNIST"
        _governmentcommunist.Caption = "Communist"
        Me.Fields.Add(_governmentcommunist)
        '
        '_governmentdemocracy
        '
        _governmentdemocracy.Name = "GOVERNMENTDEMOCRACY"
        _governmentdemocracy.Caption = "Democracy"
        Me.Fields.Add(_governmentdemocracy)
        '
        '_governmentdictatorship
        '
        _governmentdictatorship.Name = "GOVERNMENTDICTATORSHIP"
        _governmentdictatorship.Caption = "Dictatorship"
        Me.Fields.Add(_governmentdictatorship)
        '
        '_governmentmonarchy
        '
        _governmentmonarchy.Name = "GOVERNMENTMONARCHY"
        _governmentmonarchy.Caption = "Monarchy"
        Me.Fields.Add(_governmentmonarchy)
        '
        '_governmentrepublic
        '
        _governmentrepublic.Name = "GOVERNMENTREPUBLIC"
        _governmentrepublic.Caption = "Republic"
        Me.Fields.Add(_governmentrepublic)
        '
        '_governmentrevolutionary
        '
        _governmentrevolutionary.Name = "GOVERNMENTREVOLUTIONARY"
        _governmentrevolutionary.Caption = "Revolutionary"
        Me.Fields.Add(_governmentrevolutionary)
        '
        '_governmentsocialist
        '
        _governmentsocialist.Name = "GOVERNMENTSOCIALIST"
        _governmentsocialist.Caption = "Socialist"
        Me.Fields.Add(_governmentsocialist)
        '
        '_governmenttransitional
        '
        _governmenttransitional.Name = "GOVERNMENTTRANSITIONAL"
        _governmenttransitional.Caption = "Transitional"
        Me.Fields.Add(_governmenttransitional)
        '
        '_governmentother
        '
        _governmentother.Name = "GOVERNMENTOTHER"
        _governmentother.Caption = "Other"
        Me.Fields.Add(_governmentother)
        '
        '_governmentotherdesc
        '
        _governmentotherdesc.Name = "GOVERNMENTOTHERDESC"
        _governmentotherdesc.Caption = "Government other description"
        _governmentotherdesc.MaxLength = 50
        Me.Fields.Add(_governmentotherdesc)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Area in square km
    ''' </summary>
    <System.ComponentModel.Description("Area in square km")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [AREAINSQUAREKM]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _areainsquarekm
        End Get
    End Property
    
    ''' <summary>
    ''' Urban population
    ''' </summary>
    <System.ComponentModel.Description("Urban population")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [URBANPOPULATION]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _urbanpopulation
        End Get
    End Property
    
    ''' <summary>
    ''' Rural population
    ''' </summary>
    <System.ComponentModel.Description("Rural population")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RURALPOPULATION]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _ruralpopulation
        End Get
    End Property
    
    ''' <summary>
    ''' Total population
    ''' </summary>
    <System.ComponentModel.Description("Total population")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [TOTALPOPULATION]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _totalpopulation
        End Get
    End Property
    
    ''' <summary>
    ''' People groups
    ''' </summary>
    <System.ComponentModel.Description("People groups")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PEOPLEGROUPS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _peoplegroups
        End Get
    End Property
    
    ''' <summary>
    ''' Major topographical feature
    ''' </summary>
    <System.ComponentModel.Description("Major topographical feature")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MAJORTOPOGRAPHICALFEATURECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _majortopographicalfeaturecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Amharic
    ''' </summary>
    <System.ComponentModel.Description("Amharic")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEAMHARIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageamharic
        End Get
    End Property
    
    ''' <summary>
    ''' Arabic
    ''' </summary>
    <System.ComponentModel.Description("Arabic")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEARABIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagearabic
        End Get
    End Property
    
    ''' <summary>
    ''' Bengali
    ''' </summary>
    <System.ComponentModel.Description("Bengali")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEBENGALI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagebengali
        End Get
    End Property
    
    ''' <summary>
    ''' Burmese
    ''' </summary>
    <System.ComponentModel.Description("Burmese")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEBURMESE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageburmese
        End Get
    End Property
    
    ''' <summary>
    ''' Chinese
    ''' </summary>
    <System.ComponentModel.Description("Chinese")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGECHINESE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagechinese
        End Get
    End Property
    
    ''' <summary>
    ''' Creole
    ''' </summary>
    <System.ComponentModel.Description("Creole")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGECREOLE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagecreole
        End Get
    End Property
    
    ''' <summary>
    ''' English
    ''' </summary>
    <System.ComponentModel.Description("English")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEENGLISH]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageenglish
        End Get
    End Property
    
    ''' <summary>
    ''' French
    ''' </summary>
    <System.ComponentModel.Description("French")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEFRENCH]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagefrench
        End Get
    End Property
    
    ''' <summary>
    ''' Hindi
    ''' </summary>
    <System.ComponentModel.Description("Hindi")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEHINDI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagehindi
        End Get
    End Property
    
    ''' <summary>
    ''' Khmer
    ''' </summary>
    <System.ComponentModel.Description("Khmer")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEKHMER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagekhmer
        End Get
    End Property
    
    ''' <summary>
    ''' Kirghiz
    ''' </summary>
    <System.ComponentModel.Description("Kirghiz")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEKIRGHIZ]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagekirghiz
        End Get
    End Property
    
    ''' <summary>
    ''' Lao
    ''' </summary>
    <System.ComponentModel.Description("Lao")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGELAO]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagelao
        End Get
    End Property
    
    ''' <summary>
    ''' Nepali
    ''' </summary>
    <System.ComponentModel.Description("Nepali")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGENEPALI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagenepali
        End Get
    End Property
    
    ''' <summary>
    ''' Romanian
    ''' </summary>
    <System.ComponentModel.Description("Romanian")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEROMANIAN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageromanian
        End Get
    End Property
    
    ''' <summary>
    ''' Russian
    ''' </summary>
    <System.ComponentModel.Description("Russian")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGERUSSIAN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagerussian
        End Get
    End Property
    
    ''' <summary>
    ''' Inhalese
    ''' </summary>
    <System.ComponentModel.Description("Inhalese")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGESINHALESE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagesinhalese
        End Get
    End Property
    
    ''' <summary>
    ''' Siswati
    ''' </summary>
    <System.ComponentModel.Description("Siswati")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGESISWATI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagesiswati
        End Get
    End Property
    
    ''' <summary>
    ''' Spanish
    ''' </summary>
    <System.ComponentModel.Description("Spanish")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGESPANISH]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagespanish
        End Get
    End Property
    
    ''' <summary>
    ''' Swahili
    ''' </summary>
    <System.ComponentModel.Description("Swahili")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGESWAHILI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageswahili
        End Get
    End Property
    
    ''' <summary>
    ''' Tagalog
    ''' </summary>
    <System.ComponentModel.Description("Tagalog")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGETAGALOG]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagetagalog
        End Get
    End Property
    
    ''' <summary>
    ''' Tamil
    ''' </summary>
    <System.ComponentModel.Description("Tamil")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGETAMIL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagetamil
        End Get
    End Property
    
    ''' <summary>
    ''' Thai
    ''' </summary>
    <System.ComponentModel.Description("Thai")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGETHAI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languagethai
        End Get
    End Property
    
    ''' <summary>
    ''' Urdu
    ''' </summary>
    <System.ComponentModel.Description("Urdu")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEURDU]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageurdu
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _languageother
        End Get
    End Property
    
    ''' <summary>
    ''' Language other description
    ''' </summary>
    <System.ComponentModel.Description("Language other description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LANGUAGEOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _languageotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Animist
    ''' </summary>
    <System.ComponentModel.Description("Animist")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONANIMIST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionanimist
        End Get
    End Property
    
    ''' <summary>
    ''' Buddhist
    ''' </summary>
    <System.ComponentModel.Description("Buddhist")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONBUDDHIST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionbuddhist
        End Get
    End Property
    
    ''' <summary>
    ''' Catholic
    ''' </summary>
    <System.ComponentModel.Description("Catholic")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONCATHOLIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religioncatholic
        End Get
    End Property
    
    ''' <summary>
    ''' Coptic
    ''' </summary>
    <System.ComponentModel.Description("Coptic")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONCOPTIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religioncoptic
        End Get
    End Property
    
    ''' <summary>
    ''' Hindu
    ''' </summary>
    <System.ComponentModel.Description("Hindu")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONHINDU]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionhindu
        End Get
    End Property
    
    ''' <summary>
    ''' Muslim
    ''' </summary>
    <System.ComponentModel.Description("Muslim")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONMUSLIM]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionmuslim
        End Get
    End Property
    
    ''' <summary>
    ''' Orthodox
    ''' </summary>
    <System.ComponentModel.Description("Orthodox")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONORTHODOX]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionorthodox
        End Get
    End Property
    
    ''' <summary>
    ''' Protestant
    ''' </summary>
    <System.ComponentModel.Description("Protestant")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONPROTESTANT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionprotestant
        End Get
    End Property
    
    ''' <summary>
    ''' Voodoo
    ''' </summary>
    <System.ComponentModel.Description("Voodoo")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONVOODOO]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionvoodoo
        End Get
    End Property
    
    ''' <summary>
    ''' Witchcraft
    ''' </summary>
    <System.ComponentModel.Description("Witchcraft")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONWITCHCRAFT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionwitchcraft
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _religionother
        End Get
    End Property
    
    ''' <summary>
    ''' Religion other description
    ''' </summary>
    <System.ComponentModel.Description("Religion other description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RELIGIONOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _religionotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Capitalist
    ''' </summary>
    <System.ComponentModel.Description("Capitalist")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTCAPITALIST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentcapitalist
        End Get
    End Property
    
    ''' <summary>
    ''' Communist
    ''' </summary>
    <System.ComponentModel.Description("Communist")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTCOMMUNIST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentcommunist
        End Get
    End Property
    
    ''' <summary>
    ''' Democracy
    ''' </summary>
    <System.ComponentModel.Description("Democracy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTDEMOCRACY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentdemocracy
        End Get
    End Property
    
    ''' <summary>
    ''' Dictatorship
    ''' </summary>
    <System.ComponentModel.Description("Dictatorship")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTDICTATORSHIP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentdictatorship
        End Get
    End Property
    
    ''' <summary>
    ''' Monarchy
    ''' </summary>
    <System.ComponentModel.Description("Monarchy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTMONARCHY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentmonarchy
        End Get
    End Property
    
    ''' <summary>
    ''' Republic
    ''' </summary>
    <System.ComponentModel.Description("Republic")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTREPUBLIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentrepublic
        End Get
    End Property
    
    ''' <summary>
    ''' Revolutionary
    ''' </summary>
    <System.ComponentModel.Description("Revolutionary")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTREVOLUTIONARY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentrevolutionary
        End Get
    End Property
    
    ''' <summary>
    ''' Socialist
    ''' </summary>
    <System.ComponentModel.Description("Socialist")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTSOCIALIST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentsocialist
        End Get
    End Property
    
    ''' <summary>
    ''' Transitional
    ''' </summary>
    <System.ComponentModel.Description("Transitional")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTTRANSITIONAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmenttransitional
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _governmentother
        End Get
    End Property
    
    ''' <summary>
    ''' Government other description
    ''' </summary>
    <System.ComponentModel.Description("Government other description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GOVERNMENTOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _governmentotherdesc
        End Get
    End Property
    
End Class
